globalThis.SWARM_RECORDINGS = [
  {
    id: "boids",
    source: "assets/boids_good.mp4",
    diagram: "boids",
    titlePl: "Rój",
    titleEn: "Boids swarm",
    labelPl: "Ruch zbiorowy",
    labelEn: "Collective motion",
    tilePl: "Trzy proste reguły zamieniają rój w jeden organizm.",
    tileEn: "Three simple rules turn the flock into one body.",
    introPl: "To klasyczna demonstracja zachowania stadnego. Każdy dron patrzy tylko na kilku najbliższych sąsiadów i kieruje się trzema prostymi zasadami: nie wchodzić nikomu w drogę, lecieć w podobnym kierunku i nie oddalać się od grupy. Z tych lokalnych decyzji wyłania się jedna, płynna chmura dronów, która potrafi się rozproszyć i ponownie skupić, choć nikt nią nie kieruje.",
    introEn: "This is the classic flocking demonstration. Each drone looks only at a few nearby neighbours and follows three simple rules: don't crowd anyone, fly in a similar direction, and don't drift away from the group. A single, fluid cloud of drones emerges from these local decisions — able to scatter and gather again even though nothing commands it.",
    points: [
      { pl: "Każdy dron widzi tylko najbliższych sąsiadów.", en: "Each drone sees only its closest neighbours." },
      { pl: "Z trzech prostych reguł wyłania się wspólny ruch.", en: "Shared motion emerges from three simple rules." },
      { pl: "Grupa sama wraca do skupienia, bez lidera.", en: "The group gathers again on its own, with no leader." },
    ],
    facts: [
      { value: "10", labelPl: "dronów w grupie", labelEn: "drones in the flock" },
      { value: "3.0 m", labelPl: "pole sąsiedztwa", labelEn: "neighbourhood range" },
      { value: "0.5 m", labelPl: "strefa separacji", labelEn: "separation zone" },
      { value: "0.4", labelPl: "limit sterowania", labelEn: "steering limit" },
    ],
    sections: [
      {
        number: "01",
        headingPl: "Trzy reguły, jeden ruch",
        headingEn: "Three rules, one motion",
        bodyPl: "Separacja odsuwa drona od zbyt bliskiego sąsiada, wyrównanie dopasowuje jego prędkość do średniej sąsiadów, a spójność ciągnie go do ich środka. Każdy dron widzi tylko własne otoczenie, a mimo to cała grupa porusza się spójnie.",
        bodyEn: "Separation pushes a drone away from a neighbour that got too close, alignment matches its velocity to the neighbours' average, and cohesion pulls it toward their centre. Each drone only sees its own surroundings, yet the whole group moves as one.",
        formulaLabelPl: "Reguła sterująca",
        formulaLabelEn: "Steering rule",
        formulaPl: "a<sub>i</sub> = w<sub>s</sub>S<sub>i</sub> + w<sub>a</sub>A<sub>i</sub> + w<sub>c</sub>C<sub>i</sub> + w<sub>g</sub>G<sub>i</sub>",
        formulaEn: "a<sub>i</sub> = w<sub>s</sub>S<sub>i</sub> + w<sub>a</sub>A<sub>i</sub> + w<sub>c</sub>C<sub>i</sub> + w<sub>g</sub>G<sub>i</sub>",
        notePl: "w<sub>s</sub> = −1,2 jest ujemne, więc separacja odpycha. Pozostałe: w<sub>a</sub> = 0,6, w<sub>c</sub> = 2,0, w<sub>g</sub> = 0,1.",
        noteEn: "w<sub>s</sub> = −1.2 is negative, so separation repels. The rest are w<sub>a</sub> = 0.6, w<sub>c</sub> = 2.0 and w<sub>g</sub> = 0.1.",
      },
      {
        number: "02",
        headingPl: "Od sterowania do lotu",
        headingEn: "From steering to flight",
        bodyPl: "Kontroler ogranicza długość wektora sterowania do v<sub>max</sub>, a następnie przesuwa punkt docelowy drona o ten wektor w czasie τ. Punkt grawitacji dokłada przyciąganie do ustalonego miejsca, dzięki czemu rój trzyma wysokość i nie ucieka w bok.",
        bodyEn: "The controller caps the steering vector at v<sub>max</sub>, then offsets the drone's target point by that vector over the time τ. The gravity point adds a pull toward a fixed spot, which is what keeps the flock at altitude and stops it from drifting sideways.",
        formulaLabelPl: "Punkt docelowy",
        formulaLabelEn: "Target point",
        formulaPl: "p<sup>cel</sup><sub>i</sub> = p<sub>i</sub> + τ·a<sub>i</sub> + g<sub>g</sub>·(p<sub>graw</sub> − p<sub>i</sub>)",
        formulaEn: "p<sup>target</sup><sub>i</sub> = p<sub>i</sub> + τ·a<sub>i</sub> + g<sub>g</sub>·(p<sub>grav</sub> − p<sub>i</sub>)",
        notePl: "τ = 0,5 s, v<sub>max</sub> = 0,4, g<sub>g</sub> = 0,1, a punkt zaczepienia leży na wysokości 1,5 m.",
        noteEn: "τ = 0.5 s, v<sub>max</sub> = 0.4, g<sub>g</sub> = 0.1, and the anchor point sits at 1.5 m altitude.",
      },
      {
        number: "03",
        headingPl: "Co widać na nagraniu",
        headingEn: "What the recording shows",
        bodyPl: "Na starcie drony są rozrzucone daleko od siebie. W miarę jak spójność bierze górę, rój zbiega się w ciasny klaster i zawisa w jednym miejscu. Jasna plama na podłodze zdradza, jak blisko siebie lecą drony.",
        bodyEn: "At the start the drones are spread far apart. As cohesion takes over, the flock converges into a tight cluster and hovers in place. The bright patch on the floor reveals how closely the drones are flying.",
        formulaLabelPl: "Miara skupienia",
        formulaLabelEn: "Clustering measure",
        formulaPl: "spread = (1/N) · Σ ‖p<sub>i</sub> − c‖",
        formulaEn: "spread = (1/N) · Σ ‖p<sub>i</sub> − c‖",
        notePl: "c to środek masy roju. Im mniejszy spread, tym ciaśniej leci grupa.",
        noteEn: "c is the flock centre of mass. The smaller the spread, the tighter the group.",
      },
    ],
  },
  {
    id: "boids-maze",
    source: "assets/swarm_good.mp4",
    diagram: "flock-maze",
    titlePl: "Rój w labiryncie",
    titleEn: "Boids maze runner",
    labelPl: "Wspólna nawigacja",
    labelEn: "Shared navigation",
    tilePl: "Stado przechodzi labirynt jako jedna, zgrana grupa.",
    tileEn: "The flock crosses the maze as one coordinated group.",
    introPl: "Ten pokaz łączy dwa światy: planowanie trasy i zachowanie stadne. Algorytm RRT wyznacza bezpieczną drogę przez dwupokojowy labirynt, ale to rój decyduje, jak nią lecieć — trzyma się razem, omija ściany wykryte przez lidar i podąża za wspólnym celem. Efekt to grupa, która przechodzi przez wąski korytarz jak jeden organizm.",
    introEn: "This demo joins two worlds: route planning and flocking. The RRT algorithm finds a safe path through a two-room maze, but the flock decides how to fly it — staying together, avoiding walls detected by lidar, and following a shared target. The result is a group that threads a narrow corridor like a single organism.",
    points: [
      { pl: "Plan trasy i zachowanie stada działają razem.", en: "Route planning and flocking work together." },
      { pl: "Rój leci do jednego celu naraz, jako całość.", en: "The flock flies to one target at a time, as a whole." },
      { pl: "Lidar pozwala grupie przejść wąski korytarz.", en: "LiDAR lets the group pass through a narrow corridor." },
    ],
    facts: [
      { value: "5", labelPl: "dronów w grupie", labelEn: "drones in the flock" },
      { value: "6", labelPl: "promieni LiDAR na drona", labelEn: "LiDAR rays per drone" },
      { value: "2.0 m", labelPl: "zasięg LiDAR", labelEn: "LiDAR range" },
      { value: "4", labelPl: "segmenty RRT", labelEn: "RRT segments" },
    ],
    sections: [
      {
        number: "01",
        headingPl: "Najpierw plan",
        headingEn: "Plan first",
        bodyPl: "RRT rośnie w labiryncie od startu do celu: losuje punkt, znajduje najbliższy węzeł i dołącza krótki odcinek, sprawdzając po drodze kolizje co 0,1 m. Gotowa trasa przechodzi przez punkty A, C, D i T.",
        bodyEn: "RRT grows through the maze from start to target: it samples a point, finds the nearest node and attaches a short edge, checking for collisions every 0.1 m along the way. The finished route passes through A, C, D and T.",
        formulaLabelPl: "Wzrost drzewa RRT",
        formulaLabelEn: "RRT extension",
        formulaPl: "p′ = p<sub>near</sub> + min(ℓ<sub>max</sub>, ‖q − p<sub>near</sub>‖) · (q − p<sub>near</sub>) / ‖q − p<sub>near</sub>‖",
        formulaEn: "p′ = p<sub>near</sub> + min(ℓ<sub>max</sub>, ‖q − p<sub>near</sub>‖) · (q − p<sub>near</sub>) / ‖q − p<sub>near</sub>‖",
        notePl: "Odcinek ma maksymalnie 3 m, a każdy fragment trasy powstaje z budżetem 1000 iteracji.",
        noteEn: "Each edge is at most 3 m long, and every leg is planned with a budget of 1000 iterations.",
      },
      {
        number: "02",
        headingPl: "Rój trzyma się razem",
        headingEn: "The flock stays together",
        bodyPl: "Każdy dron leci do środka masy roju, zachowuje odstęp od sąsiadów i wyrównuje z nimi kierunek. Do tego dochodzi kierunek trasy oraz odpychanie od ścian wykrytych przez LiDAR; wynik jest dzielony przez liczbę punktów interpolacji i obcinany do zakresu ±0,3.",
        bodyEn: "Each drone flies toward the flock's centre of mass, keeps its distance from neighbours and matches their heading. The route direction and a push away from LiDAR-detected walls are added on top; the result is divided by the interpolation count and clipped to ±0.3.",
        formulaLabelPl: "Kierunek lotu",
        formulaLabelEn: "Flight direction",
        formulaPl: "d = clip[(F + g<sub>r</sub>û<sub>route</sub> + A) / N]",
        formulaEn: "d = clip[(F + g<sub>r</sub>û<sub>route</sub> + A) / N]",
        notePl: "F to spójność, separacja i wyrównanie, A to unikanie ścian, N = 4 punkty interpolacji, g<sub>r</sub> = 0,6.",
        noteEn: "F is cohesion, separation and alignment, A is wall avoidance, N = 4 interpolation points and g<sub>r</sub> = 0.6.",
      },
      {
        number: "03",
        headingPl: "Kiedy zmienia się cel",
        headingEn: "When the target changes",
        bodyPl: "Rój nie śledzi każdego węzła trasy osobno — leci do jednego aktywnego punktu. Gdy środek masy zbliży się do niego na 0,6 m, sterowanie przełącza się na następny. W nagraniu aktualny cel znaczy zielony krzyżyk.",
        bodyEn: "The flock does not track every route node separately — it flies to one active waypoint. When the centre of mass comes within 0.6 m of it, control switches to the next one. In the recording the current target is marked with a green crosshair.",
        formulaLabelPl: "Próg przejścia",
        formulaLabelEn: "Advance threshold",
        formulaPl: "‖w<sub>k</sub> − c‖ &lt; 0,6 m",
        formulaEn: "‖w<sub>k</sub> − c‖ &lt; 0.6 m",
        notePl: "c to środek masy roju, a w<sub>k</sub> — aktywny punkt trasy.",
        noteEn: "c is the flock centre of mass and w<sub>k</sub> is the active route node.",
      },
    ],
  },
  {
    id: "maze-runner",
    source: "assets/maze_runner_good.mp4",
    diagram: "rrt-image",
    image: "assets/RRT.png",
    imageSource: "https://www.researchgate.net/figure/Performance-of-RRT-Algorithm-1-st-Case_fig4_366866319",
    titlePl: "Robot w labiryncie",
    titleEn: "Maze runner",
    labelPl: "Nawigacja autonomiczna",
    labelEn: "Autonomous navigation",
    tilePl: "RRT planuje trasę, a sześć promieni lidaru koryguje ją na bieżąco.",
    tileEn: "RRT plans the route, and six LiDAR rays correct it on the fly.",
    introPl: "Robot najpierw planuje trasę przez labirynt, a potem leci wzdłuż niej, korygując kierunek na podstawie sześciu pomiarów lidaru. Czerwony krzyżyk pokazuje aktywny waypoint.",
    introEn: "The robot first plans a route through the maze, then flies along it, correcting its heading from six LiDAR measurements. A red crosshair marks the active waypoint.",
    points: [
      { pl: "Jeden dron planuje trasę raz, na starcie.", en: "A single drone plans the route once, at startup." },
      { pl: "Sześć promieni lidaru na bieżąco koryguje kierunek.", en: "Six LiDAR rays correct the heading on the fly." },
      { pl: "Czerwony krzyżyk pokazuje aktywny waypoint.", en: "A red crosshair marks the active waypoint." },
    ],
    facts: [
      { value: "1", labelPl: "dron", labelEn: "drone" },
      { value: "6", labelPl: "promieni LiDAR", labelEn: "LiDAR rays" },
      { value: "2.0 m", labelPl: "zasięg LiDAR", labelEn: "LiDAR range" },
      { value: "6", labelPl: "waypointów", labelEn: "waypoints" },
    ],
    sections: [
      {
        number: "01",
        headingPl: "Plan z odcinków",
        headingEn: "A plan of short edges",
        bodyPl: "RRT buduje trasę z krótkich, sprawdzonych odcinków. W tym demo pięć odcinków prowadzi przez waypointy A → B → C → D → E → F, a plan powstaje raz, na starcie, i nie jest przebudowywany w trakcie lotu.",
        bodyEn: "RRT builds the route from short, validated edges. In this demo five edges run through waypoints A → B → C → D → E → F, and the plan is computed once at startup and is not rebuilt during flight.",
        formulaLabelPl: "Krok planowania",
        formulaLabelEn: "Planning step",
        formulaPl: "p′ = extend(p<sub>near</sub>, q, ℓ<sub>max</sub>)",
        formulaEn: "p′ = extend(p<sub>near</sub>, q, ℓ<sub>max</sub>)",
        notePl: "Funkcja extend ogranicza odcinek do 3 m, a test kolizji próbkuje go co 0,1 m.",
        noteEn: "The extend function caps an edge at 3 m, and the collision test samples it every 0.1 m.",
      },
      {
        number: "02",
        headingPl: "Lidar koryguje kierunek",
        headingEn: "LiDAR bends the heading",
        bodyPl: "Sześć promieni — cztery poziome oraz po jednym w górę i w dół — mierzy odległość do ścian wokół robota. Każde trafienie tworzy odpychanie odwrotnie proporcjonalne do kwadratu odległości, więc najbliższa ściana ma największy wpływ. Ten wektor jest dodawany do kierunku waypointu i normalizowany.",
        bodyEn: "Six rays — four horizontal plus one up and one down — measure the distance to the walls around the robot. Each hit produces a repulsion inversely proportional to the squared distance, so the closest wall has the strongest effect. That vector is added to the waypoint direction and normalized.",
        formulaLabelPl: "Sterowanie kierunkiem",
        formulaLabelEn: "Heading control",
        formulaPl: "d = [A + (w − p)] / (N · ‖w − p‖)",
        formulaEn: "d = [A + (w − p)] / (N · ‖w − p‖)",
        notePl: "A = 0,2 · Σ −(h − p) / (‖h − p‖² + ε), N = 4 punkty interpolacji, ε = 10<sup>−6</sup>.",
        noteEn: "A = 0.2 · Σ −(h − p) / (‖h − p‖² + ε), N = 4 interpolation points and ε = 10<sup>−6</sup>.",
      },
      {
        number: "03",
        headingPl: "Kolejny waypoint",
        headingEn: "One waypoint at a time",
        bodyPl: "Gdy robot zbliży się do aktywnego punktu na 0,5 m, sterowanie przechodzi do następnego. Trasa jest więc realizowana krok po kroku, a czerwony krzyżyk zawsze pokazuje, dokąd zmierza robot.",
        bodyEn: "When the robot comes within 0.5 m of the active waypoint, control moves to the next one. The route is followed step by step, and the red crosshair always shows where the robot is heading.",
        formulaLabelPl: "Warunek przejścia",
        formulaLabelEn: "Advance condition",
        formulaPl: "‖w<sub>k</sub> − p‖ ≤ 0,5 m",
        formulaEn: "‖w<sub>k</sub> − p‖ ≤ 0.5 m",
        notePl: "p to pozycja robota, a w<sub>k</sub> — aktywny waypoint.",
        noteEn: "p is the robot position and w<sub>k</sub> is the active waypoint.",
      },
    ],
  },
];
